# -*- coding: utf-8 -*-
"""TASK - 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1csDYkGLNmI2Yk-1NF7SodsSuIUYMMQwo
"""

import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def password_generator():
    print("Password Generator")
    try:
        length = int(input("Enter the desired length of the password: "))
        if length <= 0:
            print("Length should be a positive integer.")
            return
    except ValueError:
        print("Invalid input. Please enter a positive integer for the length.")
        return

    password = generate_password(length)
    print(f"Generated Password: {password}")

if __name__ == "__main__":
    password_generator()